install:
		bash clean.bash
		bash install_apt-file.bash
		bash install_segondary_firmware.bash
		bash install_Nvidia_Repositery.bash
		bash install_Nvidia_Legacy_Drivers.bash
		bash install_Nvidia_Drivers.bash
	
