#!/bin/bash
# Hashrate must be in H/s (1MH = 1000000H)
hashrate_total="100000000"
# Uptime in seconds
uptime_in_sec="8452"
# Pool URL
pool="eu1.ethermine.org:4444"
# Shares
shares_accepted="500"
shares_rejected="2"

# add hashrate
# gpu0=121
# gpu1=123

# hashrate_gpu=",gpu0:$gpu0,gpu1:$gpu1,gpu2:$gpu2,gpu3:$gpu3,gpu4:$gpu4,gpu5:$gpu5,gpu6:$gpu6,gpu7:$gpu7,gpu8:$gpu8,gpu9:$gpu9,gpu10:$gpu10,gpu11:$gpu11,gpu12:$gpu12,gpu13:$gpu13,gpu14:$gpu14,gpu15:$gpu15";

# echo "error"
# exit 1

echo "hashrate_total:$hashrate_total,uptime:$uptime_in_sec,pool:$pool,shares_rejected:$shares_rejected,shares_accepted:$shares_accepted$hashrate_gpu"
