install:
		chmod 777 *.bash
		./clean.bash
		./install_apt-file.bash
		./install_segondary_firmware.bash
		./install_Nvidia_Repositery.bash
		./install_Nvidia_Legacy_Drivers.bash
		./install_Nvidia_Drivers.bash