#!/bin/sh
# -a octopus -o stratum+tcp://cfx-eu1.nanopool.org:17777 -u cfx:aajauymfc0cpd4aj91wmfyd150avfg3fmym9j2xrh8.rig0/your@email.org -p x -lock-cclock 1310 --mclock 1400 --fan 80 -Ihr-autotune-step-size 0.1 --Ihr-autotune-interval 5
config_miner =" -a octopus -o "
url_pool = "stratum+tcp://cfx-eu1.nanopool.org:17777"
wallet ="cfx:aajauymfc0cpd4aj91wmfyd150avfg3fmym9j2xrh8"
name ="rig0" 
mail = "your@email.org"
over_config ="-lock-cclock 1310 --mclock 1400 --fan 80 -Ihr-autotune-step-size 0.1 --Ihr-autotune-interval 5"

config = $config_miner $url_pool -u $wallet.$name/$email -p x $over_config
